name: SfChunkInfo
version: ${project.version}
main: me.fnfal113.sfchunkinfo.SfChunkInfo
api-version: 1.14
authors: [ FN_FAL113 ]
description: Scan the amount of Slimefun blocks in a chunk
depend: [Slimefun]
commands:
  sfchunkinfo:
    description: Scan chunk for amount of slimefun machines
    permission: sfchunkinfo.scan
    usage: /<command>